### ISSUE TITLE
免费提供一个域名

### ISSUE THREAD

**Issue by lizhimusic** [GoldSubmarine/lizhi#10]
[https://lizhiyun.live/](https://lizhiyun.live/)
之前搞得一个域名，现在已经用Cloudflare的workers进行对GoldSubmarine.github.io进行反向代理了，打开速度还可以，域名也好记 李志云.现场 建议添加

**Comment by Nayacco** [comment]
感谢你的付出，已添加

**Comment by Nayacco** [comment]
你好，貌似现在 https 证书有问题

**Comment by lizhimusic** [comment]
忘记告诉你了，那个域名到期了没续费，然后现在准备用的lizhi.yaojiu.us反代你那个，然后我自己整理了一点是lz.yaojiu.us
，还没反代，回家后反代，或者lizhi.haoo.us

GoldSubmarine ***@***.***>于2021年7月3日 周六15:21写道：

**Comment by lizhimusic** [comment]
反代完成了 [https://lizhi.yaojiu.us/](https://lizhi.yaojiu.us/)和备用[https://lizhi.yaojiu.workers.dev/](https://lizhi.yaojiu.workers.dev/) 用Cloudflare workers容器反向代理的比较稳定，我自己整理的[https://lz.yaojiu.us/](https://lz.yaojiu.us/)  上面的域名过期了
