### ISSUE TITLE
jsdelivr  `list.js` 访问报错 

### ISSUE THREAD

**Issue by sjfkai** [GoldSubmarine/lizhi#11]
访问： https://cdn.jsdelivr.net/gh/goldsubmarine/lizhi-resource@master/audio/list.js， 403报错：

```
Package size exceeded the configured limit of 50 MB. Try https://github.com/goldsubmarine/lizhi-resource/tree/master/audio/list.js instead.
```

看描述是因为 lizhi-resource 项目 package 太大了
但是访问  https://cdn.jsdelivr.net/gh/GoldSubmarine/lizhi-resource@master/audio/list.js 就没有问题
另外 mp3 、 cover 访问原 url 目前也没有问题， 只有 list.js 报错了

不知道直接修改大小写能不能解决问题

**Comment by Nayacco** [comment]
应该是 jsdelivr 抽风了，这个文件没有超过50M，等一会就好了

**Comment by Nayacco** [comment]
额，我刚才看错你的回复了，小写也是可以访问的，你试一下呢，现在我这是没有问题
