### ISSUE TITLE
提供2019洗心革面跨年音乐会完整版在线播放链接

### ISSUE THREAD

**Issue by wallyperry** [GoldSubmarine/lizhi#4]
作者你好，感谢作出这样一个播放器，我这边提供一个2019洗心革面跨年音乐会完整版在线播放链接：
https://beenet-boss.oss-cn-shenzhen.aliyuncs.com/2019/05/28/m3u8/洗心革面/playlist.m3u8
另外，我这边也写了一个安卓客户端，下载地址：https://lz.perry.ren

**Comment by Nayacco** [comment]
这个资源是存在阿里云上的，不能保证资源一直有效，可以的话上传到 github 上吧

**Comment by lunxian8** [comment]
> 作者你好，感谢作出这样一个播放器，我这边提供一个2019洗心革面跨年音乐会完整版在线播放链接：
> [https://beenet-boss.oss-cn-shenzhen.aliyuncs.com/2019/05/28/m3u8/洗心革面/playlist.m3u8](https://beenet-boss.oss-cn-shenzhen.aliyuncs.com/2019/05/28/m3u8/%E6%B4%97%E5%BF%83%E9%9D%A9%E9%9D%A2/playlist.m3u8)
> 另外，我这边也写了一个安卓客户端，下载地址：https://lz.perry.ren

老铁，只有安卓版你怎么搞了个苹果的logo
