### ISSUE TITLE
老哥稳，要是给下载就好了。之前在百度云盘的视频全被封了。。。

### ISSUE THREAD

**Issue by littlepriest** [GoldSubmarine/lizhi#9]

**Comment by Nayacco** [comment]
下载你指的视频吗？

视频要在网页中分段加载，所以切成一小段一小段的了，可以自己找个工具下载合并，不过在我看来没有下载的必要，因为资源永远不会过期，除非github倒闭，所以直接网页上看就好

**Comment by littlepriest** [comment]
也行，谢谢老哥了。

昨晚我试了一下不开 vpn 上 github， 几乎打不开。另外，哔哩哔哩等一堆地方求资源的，都是很多骗关注公众号的，卖盗来的资源的。一声叹息。

甚至还有人在这上面建了个仓，明着说免费送资源，其实点进去还是一个关注公众号或者小程序的图。。。吃相难看了点。

**Comment by Nayacco** [comment]
打不开应该是域名被DNS污染的原因，资源走的是CDN不是github，刚刚我增加了一个cloudflare的网页，可以直接打开
